#!/usr/bin/env bash

# Exit immediately if any command returns a non-zero status
set -e

# Trap any errors and print a message.
trap 'echo "Something went wrong!"' ERR

# Check if the number of arguments is greater than 1 or if the argument contains spaces
if [[ $# -gt 1 ]] || [[ $1 == *" "* ]]; then
    echo "Only one argument without spaces is allowed for the project name."
    exit 1
fi

# If an argument is passed, set it as the project name, otherwise prompt the user for it
if [[ $# -eq 1 ]]; then
    project_name="$1"
else
    echo -n "Enter the project name: "
    read project_name
fi

# Check if a directory with the given project name already exists
if [ -d "$project_name" ]; then
    echo "Directory $project_name already exists!"
    exit 1  # Exit the script with a status of 1 indicating an error.
fi

# Create the main project directory and its subdirectories
mkdir -p "$project_name"/{source_files,header_files,build}

# Create a .vimspector.json file inside the project directory with the provided contents
cat > "$project_name"/.vimspector.json <<EOL
{
  ### .vimspector.json contents here ###
}
EOL

# Success message
echo "C++ project $project_name created successfully!"

