theme = "github_dark_dimmed"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
true-color = true
mouse = false
line-number = "relative"
bufferline = "multiple"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false